 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/challenges", type: :request do
  # Manager::Challenge. As you add validations to Manager::Challenge, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Manager::Challenge.create! valid_attributes
      get manager_student_challenges_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      challenge = Manager::Challenge.create! valid_attributes
      get manager_student_challenge_url(manager_student_challenge)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_manager_student_challenge_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      challenge = Manager::Challenge.create! valid_attributes
      get edit_manager_student_challenge_url(manager_student_challenge)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Manager::Challenge" do
        expect {
          post manager_student_challenges_url, params: { manager_student_challenge: valid_attributes }
        }.to change(Manager::Challenge, :count).by(1)
      end

      it "redirects to the created manager_student_challenge" do
        post manager_student_challenges_url, params: { manager_student_challenge: valid_attributes }
        expect(response).to redirect_to(manager_student_challenge_url(@manager_student_challenge))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Manager::Challenge" do
        expect {
          post manager_student_challenges_url, params: { manager_student_challenge: invalid_attributes }
        }.to change(Manager::Challenge, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post manager_student_challenges_url, params: { manager_student_challenge: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested manager_student_challenge" do
        challenge = Manager::Challenge.create! valid_attributes
        patch manager_student_challenge_url(manager_student_challenge), params: { manager_student_challenge: new_attributes }
        challenge.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the manager_student_challenge" do
        challenge = Manager::Challenge.create! valid_attributes
        patch manager_student_challenge_url(manager_student_challenge), params: { manager_student_challenge: new_attributes }
        challenge.reload
        expect(response).to redirect_to(manager_student_challenge_url(challenge))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        challenge = Manager::Challenge.create! valid_attributes
        patch manager_student_challenge_url(manager_student_challenge), params: { manager_student_challenge: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested manager_student_challenge" do
      challenge = Manager::Challenge.create! valid_attributes
      expect {
        delete manager_student_challenge_url(manager_student_challenge)
      }.to change(Manager::Challenge, :count).by(-1)
    end

    it "redirects to the manager_student_challenges list" do
      challenge = Manager::Challenge.create! valid_attributes
      delete manager_student_challenge_url(manager_student_challenge)
      expect(response).to redirect_to(manager_student_challenges_url)
    end
  end
end
